---
- hosts: all 
  vars:
    ansible_user: vagrant 
    ansible_password: vagrant
    ansible_connection: winrm
    ansible_port: 5986
    ansible_winrm_server_cert_validation: ignore
    
  roles:
    #- win_template-fail
    - win-copy-error
